# Generated by Django 4.0.5 on 2022-06-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('start_dt', models.DateTimeField(blank=True, db_column='START_DATETIME', null=True)),
                ('end_dt', models.DateTimeField(blank=True, db_column='END_DATETIME', null=True)),
                ('type', models.CharField(choices=[(1, 'Normal'), (2, 'Mission')], db_column='TYPE', default='Normal', max_length=25)),
                ('explanation', models.TextField(blank=True, db_column='EXPLANATION', null=True)),
                ('image', models.ImageField(db_column='IMAGE', null=True, upload_to='')),
            ],
            options={
                'db_table': 'SM_EVENT',
                'ordering': ['pk'],
            },
        ),
    ]
