# Generated by Django 4.0.5 on 2022-06-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('name', models.CharField(db_column='EVENT_NAME', max_length=100)),
                ('start_dt', models.DateTimeField(db_column='START_DATETIME')),
                ('end_dt', models.DateTimeField(db_column='END_DATETIME')),
                ('type', models.CharField(choices=[(1, 'Normal'), (2, 'Mission')], db_column='TYPE', default='Normal', max_length=25)),
                ('explanation', models.TextField(blank=True, db_column='EXPLANATION', null=True)),
                ('image', models.ImageField(db_column='IMAGE', null=True, upload_to='')),
                ('inner_exhibition', models.ForeignKey(db_column='INNER_EXHIBITION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='museum.innerexhibition')),
            ],
            options={
                'db_table': 'SM_EVENT',
                'ordering': ['pk'],
            },
        ),
    ]
