# Generated by Django 4.0.5 on 2022-06-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('beacon_id', models.BigIntegerField(db_column='BEACON_ID')),
                ('recent_reception', models.DateTimeField(db_column='REACT_RECEPTION')),
            ],
        ),
    ]
