# Generated by Django 4.0.5 on 2022-07-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='beacon',
        ),
        migrations.DeleteModel(
            name='DayLog',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
