# Generated by Django 4.0.5 on 2022-07-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beacon',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(db_column='UUID', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='beacon',
            unique_together={('id', 'uuid')},
        ),
    ]
