# Generated by Django 4.0.5 on 2022-07-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daylog',
            old_name='viewing_time_count',
            new_name='time_count',
        ),
    ]
