# Generated by Django 4.0.5 on 2022-07-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_innerexhibition_x_coordinate_and_more'),
        ('beacon', '0003_alter_beacon_inner_exhibition'),
        ('history', '0002_rename_viewing_time_count_daylog_time_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylog',
            name='inner_exhibition',
            field=models.ForeignKey(db_column='INNER_EXHIBITION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_log', to='museum.innerexhibition'),
        ),
        migrations.AlterField(
            model_name='log',
            name='beacon',
            field=models.ForeignKey(db_column='BEACON_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='beacon.beacon'),
        ),
    ]
