# Generated by Django 4.0.5 on 2022-07-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_daylog_inner_exhibition_alter_log_beacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='daylog',
            name='footprint',
            field=models.JSONField(db_column='FOOT_PRINT', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='mac_address',
            field=models.CharField(db_column='MAC_ADDRESS', default=1, max_length=25),
            preserve_default=False,
        ),
    ]
