# Generated by Django 4.0.5 on 2022-07-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_log_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daylog',
            name='footprint',
        ),
    ]
