# Generated by Django 4.0.5 on 2022-07-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_innerexhibition_x_coordinate_and_more'),
        ('history', '0008_alter_footprintlog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprintlog',
            name='exhibition',
            field=models.ForeignKey(db_column='EXHIBITION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foot_print', to='museum.exhibition'),
        ),
    ]
