# Generated by Django 4.0.5 on 2022-06-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('floor_ko', models.CharField(db_column='FLOOR_KO', max_length=25)),
                ('floor_en', models.CharField(db_column='FLOOR_EN', max_length=25)),
                ('house_ko', models.CharField(db_column='HOUSE_KO', max_length=25, null=True)),
                ('house_en', models.CharField(db_column='HOUSE_EN', max_length=25, null=True)),
                ('drawing_image', models.ImageField(blank=True, db_column='DRAWING_IMAGE', upload_to='')),
            ],
            options={
                'db_table': 'SM_EXHIBITION',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='InnerExhibition',
            fields=[
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('beacon', models.BigIntegerField(db_column='BEACON_ID', null=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('vr_link', models.URLField(db_column='VR_LINK', null=True)),
                ('order', models.IntegerField(db_column='ORDER', primary_key=True, serialize=False)),
                ('explanation', models.TextField(blank=True, db_column='EXPLANATION', null=True)),
                ('image', models.ImageField(db_column='IMAGE', null=True, upload_to='')),
                ('exhibition', models.ForeignKey(db_column='EXHIBITION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_exhibition', to='museum.exhibition')),
            ],
            options={
                'db_table': 'SM_INNER_EXHIBITION',
                'ordering': ['pk', 'order'],
            },
        ),
    ]
