# Generated by Django 4.0.5 on 2022-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerexhibition',
            name='x_coordinate',
            field=models.CharField(blank=True, db_column='X_COORDINATE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='innerexhibition',
            name='y_coordinate',
            field=models.CharField(blank=True, db_column='Y_COORDINATE', max_length=10, null=True),
        ),
    ]
