# Generated by Django 4.0.5 on 2022-06-16 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition', to=settings.AUTH_USER_MODEL),
        ),
    ]
