# Generated by Django 4.0.5 on 2022-06-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_exhibition_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerexhibition',
            name='beacon',
        ),
    ]
